### ISSUE TITLE
Find alternative to Aggressive Indent

### ISSUE THREAD

**Issue by raxod502** [raxod502/radian#383]
Unfortunately, Aggressive Indent is slow. Also, it pains me to go back to Electric Indent for languages that aren't good for Aggressive Indent, like C++. I think the best solution is to smartly figure out exactly what needs to be reindented, and only reindent that. Or something. But the emphasis needs to be on performance; Radian Emacs should be snappy.

**Comment by alphapapa** [comment]
These tags are amazing.  :D 

Curious, how have you discovered that agg-indent is slow?  I use it with elisp and it seems to work well enough.  However, I do get some stuttering in Emacs sometimes, and although I don't think it's related, if it turned out to be...

**Comment by raxod502** [comment]
It's heavily dependent on major mode. The situation is much worse in Clojure, for example, where computing indentation sometimes involves communicating with an external process (the Clojure REPL). And I have seen lag in Elisp, although not nearly as frequently.

I get lots of stuttering in Emacs, and it's due to a variety of things, which I really need to nail down and eliminate. Smartparens, Aggressive Indent, Company, ElDoc, Flx, and so on. It's because a lot of those packages do not have designs which scale well (performance-wise) to a workflow in which they're called very frequently.

**Comment by raxod502** [comment]
In particular, try doing some nontrivial work on `startup.el` with Aggressive Indent enabled. There's about a 0.75s delay on saving the buffer, often, since Aggressive Indent wants to reindent the current function (many hundred lines) on save.

**Comment by raxod502** [comment]
Aggressive Indent removed in https://github.com/raxod502/radian/commit/e008f4df06ffae839eaeb35d45eae8d6e6f2abfe.

**Comment by alphapapa** [comment]
So I guess you determined that aggressive-indent was irredeemable?  :)

**Comment by raxod502** [comment]
The lag combined with the bug discussed at https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-06/msg00093.html (which has _not_ gone away on applying the patch that came out of the discussion) means it's a better UX to manually indent than to use `aggressive-indent-mode`.

I will be working on adding specifically targeted features such as reindent on paste.

**Comment by alphapapa** [comment]
Thanks for the pointer to that bug.  I wonder if it could be related in any way to a problem I've been experiencing for a while: When I have two windows open on the same buffer, side-by-side, and I type in one of them, quite often the focus will suddenly, in the middle of my typing, switch to the other window, and cause my input to go to a different point in the buffer.  I'm guessing it's something to do with my personal config, a bug in some package or something, but your report reminded me of it, because when I `view-lossage` immediately after it happens, I don't see any extra keystrokes, nothing that should have caused the window to be switched.
