### ISSUE TITLE
rust mode is unbearably slow 

### ISSUE THREAD

**Issue by redpanda1234** [raxod502/radian#392]
Occasionally have to wait more than half a second for keypresses to register. Not quite sure what the issue is.

**Comment by raxod502** [comment]
Try disabling `eldoc-mode` and/or `company-mode` and/or `racer-mode`, and seeing which is the problem.

**Comment by redpanda1234** [comment]
Seems that racer-mode is the main bottleneck. Toggling `eldoc-mode` and `company-mode` appear (?) to cause small performance hits, but `racer-mode` I think is what really kills it.

**Comment by raxod502** [comment]
That's what I figured. Try

```
$ emacs -nw -Q -l ~/.emacs.d/straight/bootstrap.el
```

and `M-x straight-use-package RET racer RET`, find a Rust file, `M-x racer-mode` and see if you can reproduce the lag. You may also need to install `company`. If you can reproduce it in vanilla Emacs, then I would recommend reporting the issue upstream; otherwise, try to bisect. I probably won't have time to debug for a while.

**Comment by redpanda1234** [comment]
Additionally: `C-s` occasionally freezes emacs for >5 seconds.

**Comment by redpanda1234** [comment]
<img width="711" alt="screen shot 2017-12-03 at 8 35 42 pm" src="https://user-images.githubusercontent.com/25603060/33536397-a219290e-d869-11e7-96dd-2ca8b68702e6.png">

**Comment by raxod502** [comment]
It looks like the bottleneck is `adaptive-wrap-prefix-mode`. You could turn that off in `rust-mode`, or submit an issue upstream.

I'm not entirely convinced that `adaptive-wrap-prefix-mode` is even that useful. I might want to just get rid of it entirely.

**Comment by redpanda1234** [comment]
All-around performance is substantially improved after disabling `adaptive-wrap-prefix-mode`.
