### ISSUE TITLE
Default font faces are yuck 

### ISSUE THREAD

**Issue by redpanda1234** [raxod502/radian#396]
For instance, section header sizing in latex-mode is obnoxious and gross in my opinion. 

I'm not sure how to properly address this. I've just been customizing all of them through `M-x describe-face RET` but I imagine this is dumb and improper and all that. How should I go about properly addressing it, if I want to make things look the way they did in terminal emacs?

**Comment by redpanda1234** [comment]
Also, I recognize that you aren't stackexchange, and that I probably should find a solution myself instead of asking you. However, radian is large, and I am a little daunted by trying to go through and figure it all out on my own. Hence I figured I should at least submit an issue report here for the time being. I will also look into this myself once finals have passed.

**Comment by raxod502** [comment]
[This question](https://stackoverflow.com/q/7860547/3538165) suggests that there is no general solution. Most packages should probably variables for customizing the fontification, however, such as [`font-latex-fontify-sectioning`](https://tex.stackexchange.com/a/176787/54018) for AUCTeX. I recommend avoiding Custom whenever possible, since it hurts the readability of your configuration. Everything can be done in pure Emacs Lisp.

Open a new issue if you have a more specific problem :)
