### ISSUE TITLE
pipe character is lower relative to other characters on the same line?

### ISSUE THREAD

**Issue by redpanda1234** [raxod502/radian#403]
<img width="111" alt="screen shot 2017-12-09 at 5 32 07 pm" src="https://user-images.githubusercontent.com/25603060/33801163-fb298560-dd06-11e7-982e-323a98e94b03.png">

**Comment by raxod502** [comment]
That sounds like a problem with your font. Does it reproduce in `emacs -Q`?

**Comment by raxod502** [comment]
This issue is being closed automatically since it has a "waiting on response" label but hasn't had any activity in 90 days. But don't worry: if you have some information to help move the discussion along, just leave a comment and I'll re-open the issue.

*(Comment generated automatically by [NO CARRIER](https://github.com/twbs/no-carrier) via [tidier](https://github.com/raxod502/tidier).)*
