### ISSUE TITLE
Why enable projectile-mode?

### ISSUE THREAD

**Issue by wedens** [raxod502/radian#437]
I've noticed that you disabled all of what `projectile-mode` does via lots of code using el-patch.

I'm curious, why not just avoid enabling `projectile-mode` and avoid copy-pasting ~200loc? 🙂  Projectile seems to work just fine without  `projectile-mode`.

**Comment by raxod502** [comment]
It's necessary because `counsel-projectile` requires for `projectile-command-map` and `projectile-mode-map` to be defined. If we don't lazy-load Projectile the way we do, then `counsel-projectile` can't define its keybindings without loading Projectile anyway.

Also, you definitely do need to enable `projectile-mode` at some point. Otherwise, new projects aren't added to the list of known projects. The natural thing to do is to enable `projectile-mode` only after `projectile` is actually loaded, and then handle the `projectile-mode-map` keybindings as part of the lazy-loading, but as I said above this doesn't work because of `counsel-projectile`.
