### ISSUE TITLE
Using radian with chemacs.

### ISSUE THREAD

**Issue by 4goodapp** [raxod502/radian#440]
I tried to use [chemacs](https://github.com/plexus/chemacs)  to test radian but it doesn't work.
How to configure it with chemacs?

**Comment by raxod502** [comment]
Have you followed the symlinking instructions in the README? I don't use this tool (Radian implements a profile switching system itself, by means of the `USER_EMACS_DIRECTORY` environment variable), but it seems like it should work fine to link the requisite Radian files into a separate directory to serve as `user-emacs-directory`, and then configure this directory for use with chemacs.

**Comment by 4goodapp** [comment]
I just added the following:

```
(("default" . ((user-emacs-directory . "~/.emacs.d")))              ;; DoomEmacs, my default emacs
 ("prelude" . ((user-emacs-directory . "~/EMACS_CONFIGS/prelude"))) ;; Prelude
 ("spacemacs" . ((user-emacs-directory . "~/EMACS_CONFIGS/spacemacs/.emacs.d"))) ;; Spacemacs

 ("radian" . ((user-emacs-directory . "~/EMACS_CONFIGS/radian/emacs/"))) ;; radian. By Straight.el package maker.
 )

```

It usually work like this

Changed this line too:

```
    (defvar radian-local-init-file "~/.emacs.d/init.local.el"
      "File for local customizations of Radian.")
```
to be:
```
    (defvar radian-local-init-file "~/EMACS_CONFIGS/radian/emacs/"
      "File for local customizations of Radian.")
```
but still having the same issue.

**Comment by raxod502** [comment]
You need to follow the symlinking instructions in the README. The `emacs` subdirectory of this repository will not function as a `user-emacs-directory`. If you don't want to link the files directly into `~/.emacs.d`, you need to create a new directory and link them into that directory, as per the instructions.

Separately, I have pushed a commit which makes sure that various other functions in Radian will function as desired with `user-emacs-directory` set to a nonstandard value.

**Comment by 4goodapp** [comment]
Thanks for the support. 
You can close the issue. I test straight on my setup and it downloaded about 340mb of data by cloning repositories of each package I have on my init file, which is a very slow process unfortunately.

Off topic:
What's the point of having Melpa in straight if download the repos of a package? why can't it just download directly from melpa? Is there an option for that?
The only package I need for an external repos is Bookmark+. 
And straight download about 100mb of data for that package alone.

**Comment by raxod502** [comment]
If you don't want to clone Git repositories, then it sounds like you don't want to use `straight.el`. The entire point of `straight.el` is to clone Git repositories. Downloading tarballs from MELPA is an antipattern given the design goals of `straight.el` and is completely unsupported.

But of course it also needs to clone MELPA. Otherwise how would it know where to find the Git repositories for packages?

**Comment by 4goodapp** [comment]
Thanks for the explanation :)

**Comment by raxod502** [comment]
See also https://github.com/raxod502/straight.el/issues/149 for improving performance of cloning Git repos initially.

**Comment by 4goodapp** [comment]
Thanks :)

**Comment by oatmealm** [comment]
Can you explain how to set it up for chemacs 2.0 if possible? It occupies `emacs.d`. Iv'e tried this, but with the require init files simlinked into `USER_EMACS_DIRECTORY` I'm getting:

```
error: Recursive load, /home/uri/.config/radian/init.el, /home/uri/.config/radian/init.el, /home/uri/.config/radian/init.el, /home/uri/.config/radian/init.el, /home/uri/.config/radian/init.el, /home/uri/src/radian-emacs/emacs/init.el, /home/uri/.emacs.d/init.el
```

**Comment by raxod502** [comment]
I believe you would want to have `((user-emacs-directory . "~/.config/radian"))` if that's where you are symlinking the dotfiles, no?

**Comment by oatmealm** [comment]
AFAIK user-emacs-directory is the base directory of the distribution itself ... I'm note sure then where to link my personal config files...

**Comment by raxod502** [comment]
Radian expects to be symlinked, hence the recursive load error. If you don't want to symlink into `~/.emacs.d` directly, e.g. because you're using chemacs, I would suggest creating a directory like `~/.config/radian`, and then symlinking the Radian dotfiles into that directory. I.e.,

* `~/.config/radian` is an ordinary directory
* `~/.config/radian/init.el` is a symlink to `~/src/radian-emacs/emacs/init.el`
* `~/.config/radian/straight/versions/radian.el` is a symlink to `~/src/radian-emacs/emacs/versions.el`
* `~/.config/radian/init.local.el` is your local configuration file for Radian

Then you would set `user-emacs-directory` to `~/.config/radian`.
