### ISSUE TITLE
Unable to add org-plus-contrib

### ISSUE THREAD

**Issue by peschkaj** [raxod502/radian#442]
Typically I use org-mode with org-plus-contrib like so:

```
(use-package org
  :ensure org-plus-contrib
  ... )
```

I attempted adding `:ensure org-plus-contrib` to radian.el, but that does not appear to have fixed anything.

Is there a way to accomplish this with radian and/or straight.el?

**Comment by raxod502** [comment]
```
(straight-use-package 'org-plus-contrib)
```

? You shouldn't be using `:ensure`, as that is for `package.el` integration which we don't use. I recommend reading the `straight.el` documentation on Org and `use-package`.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
