### ISSUE TITLE
README errors 

### ISSUE THREAD

**Issue by redpanda1234** [raxod502/radian#443]
1. In the Arch/Manjaro Linux section under Code intelligence, you suggest installing `bash-language-server` using `yarn`. It appears the package is available through `pacman`; is there any reason to use `yarn` instead? 

2. For local configuration, you suggest symlinking `~/.emacs.d/init.local.el` to `~/.emacs.d/straight/versions/radian-local.el`.  However, `C-h v radian-local-init-file` lists `~/.emacs.d/init.local.el` instead. Is this intentional?

**Comment by raxod502** [comment]
1. Last time I checked, the official package for `bash-language-server` did not work, while the one from Yarn did.
2. I don't suggest making a symlink for local configuration. README has been reworded.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)
