### ISSUE TITLE
How to disable packages that Radian loads

### ISSUE THREAD

**Issue by haji-ali** [raxod502/radian#475]
Is there a way to disable packages that Radian loads without modifying Radian?

For example, I want to disable `undo-tree` (too buggy) and use the simpler `undo-fu` in my config. It would be even better if I can set up Radian so as not to clone/build `undo-tree` at all.

(PS: Sorry for the many questions. I am switching my setup to use more "pure" Emacs packages like `selectrum`, `ctrlf`, `embark` and `consult`, and I appreciate that Radian makes it easy.)

**Comment by raxod502** [comment]
Unfortunately, there is no general mechanism for doing this at present. I think a reasonable way to do it would be, for each such package, introduce a user option analogous to `radian-color-theme-enable` (which currently does what you describe for `zerodark-theme`). It might be desirable to do it this way, in fact, because by curating the set of user options, we can make sure that disabling a package also disables all dependent packages and other configuration that might break when the package is disabled.

**Comment by haji-ali** [comment]
Yeah, I think something a variable like `radian-features` containing a list of packages that Radian can use, and  corresponding `:if` statements in all the `use-package` and `use-feature` statements would do the trick.

**Comment by raxod502** [comment]
That sounds reasonable. I like the idea of a list more than individual variables, I think.
